language: ruby
rvm:
  - 2.3.0

env:
  - DB=sqlite

script:
  - RAILS_ENV=test
  - bundle exec rake db:migrate --trace
  - bundle exec rspec spec
  - bundle exec rake cucumber
  - bundle exec rake :test_with_coveralls

after_success:
  - coveralls
